server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
      username: root
      password: root
  boot:
    admin:
      client:
        url: http://localhost:8080

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

info:
  appName: @project.artifactId@
  version: @project.version@
  company: 传智教育
  author: itheima

#tools:
#  ip:
#    cycle: 1
#    cycle-reset: false
#    model: "detail"
tools:
  ip:
    cycle-reset: false
    cycle: 1
    model: detail


#设置Mp相关的配置
mybatis-plus:
  global-config:
    db-config:
      #设置所有表的通用前缀名称为tbl_
      table-prefix: tbl_
      #设置主键id字段的生成策略为参照数据库设定的策略，当前数据库设置id生成策略为自增
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
